{
 "title": "Query Insights",
 "tags": [ "query-insights" ],
 "time": { "from": "2022-12-22T07:03:16.683Z", "to": "2022-12-22T07:32:25.798Z" },
 "templating": {
  "list": [
   { "name": "pds", "label": "Prometheus", "query": "prometheus" },
   { "name": "project", "label": "Project", "query": { "query": "label_values(project_id)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance_id)" } },
   { "name": "database", "label": "Database", "query": { "query": "label_values(database)" } },
   {
    "name": "query_topn",
    "label": "Top 10 Queries",
    "query": {
     "query": "query_result(topk(10, avg_over_time(database_spanner_query_stats_top_avg_cpu_seconds[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total (all queries)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_avg_cpu_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Average bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_avg_bytes{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Average execution latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_avg_latency_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "p99 execution latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_ninety_nine_percentile_latency{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "p95 execution latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_ninety_five_percentile_latency{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "p50 execution latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_fifty_percentile_latency{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Execution count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_execution_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Average execution failed latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_all_failed_avg_latency_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Timed out execution count ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_timed_out_execution_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Failed execution count ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_all_failed_execution_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Average rows returned",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_avg_rows{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Cancelled or Disconnected execution count ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_cancelled_or_disconnected_execution_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Average rows scanned",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "database_spanner_query_stats_total_avg_rows_scanned{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Top Queries (per query)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Average CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_avg_cpu_seconds{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Average bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_avg_bytes{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\",project_id=~\"$project\",project_id=~\"$project\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Average execution latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_avg_latency_seconds{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "p99 execution latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_ninety_nine_percentile_latency{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "p95 execution latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_ninety_five_percentile_latency{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "p50 execution latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_fifty_percentile_latency{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Execution count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_execution_count{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Average failed execution  latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_all_failed_avg_latency_seconds{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Timed out execution count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sum by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_timed_out_execution_count{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Failed execution count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "sum by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_all_failed_execution_count{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Average rows returned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_avg_rows{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\",project_id=~\"$project\",project_id=~\"$project\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Cancelled or disconnected execution count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "sum by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_cancelled_or_disconnected_execution_count{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Average rows scanned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_avg_rows_scanned{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\",project_id=~\"$project\",project_id=~\"$project\"})",
     "legendFormat": "{{query_text_fingerprint}}"
    }
   ]
  },
  {
   "title": "Top Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "database_spanner_query_stats_top_avg_latency_seconds{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"}"
    },
    {
     "expr": "database_spanner_query_stats_top_avg_rows_scanned{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\",project_id=~\"$project\"}"
    },
    {
     "expr": "database_spanner_query_stats_top_execution_count{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"}"
    },
    {
     "expr": "database_spanner_query_stats_top_avg_cpu_seconds{query_text_fingerprint=~\"$query_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"}"
    }
   ]
  }
 ]
}