{
 "title": "Google Cloud Spanner - Query details",
 "description": "Query details dashboard",
 "tags": [ "query-details" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "pds", "label": "Prometheus", "query": "prometheus" },
   { "name": "project", "label": "Project", "query": { "query": "label_values(project_id)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance_id)" } },
   { "name": "database", "label": "Database", "query": { "query": "label_values(database)" } },
   {
    "name": "query_topn",
    "label": "Top 10 Queries",
    "query": {
     "query": "query_result(topk(10, avg_over_time(database_spanner_query_stats_top_avg_cpu_seconds[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_avg_cpu_seconds{query_text_fingerprint=\"${query_topn}\", database=\"$database\", instance_id=\"$instance\", project_id=\"$project\"})",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_avg_latency_seconds{query_text_fingerprint=\"$query_topn\", database=\"$database\", instance_id=\"$instance\", project_id=\"$project\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Execution count / Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (project_id,instance_id,database,query_text) (database_spanner_query_stats_top_execution_count{query_text_fingerprint=\"$query_topn\",database=\"$database\",instance_id=\"$instance\",project_id=\"$project\"})",
     "legendFormat": "Execution count"
    },
    {
     "expr": "sum by (project_id,instance_id,database,query_text) (database_spanner_query_stats_top_all_failed_execution_count{query_text_fingerprint=\"$query_topn\",database=\"$database\",instance_id=\"$instance\",project_id=\"$project\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Rows scanned / Rows returned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_avg_rows_scanned{query_text_fingerprint=\"$query_topn\", database=\"$database\",instance_id=\"$instance\",project_id=\"$project\"})",
     "legendFormat": "Scanned"
    },
    {
     "expr": "avg by (project_id,instance_id,database,query_text)(database_spanner_query_stats_top_avg_rows{query_text_fingerprint=\"$query_topn\",database=\"$database\",instance_id=\"$instance\",project_id=\"$project\"})",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "database_spanner_query_stats_top_avg_latency_seconds{query_text_fingerprint=\"$query_topn\",database=\"$database\", instance_id=\"$instance\",project_id=\"$project\"}"
    },
    {
     "expr": "database_spanner_query_stats_top_avg_rows_scanned{query_text_fingerprint=\"$query_topn\",database=\"$database\",instance_id=\"$instance\",project_id=\"$project\"}"
    },
    {
     "expr": "database_spanner_query_stats_top_execution_count{query_text_fingerprint=\"$query_topn\",database=\"$database\", instance_id=\"$instance\",project_id=\"$project\"}"
    },
    {
     "expr": "database_spanner_query_stats_top_avg_cpu_seconds{query_text_fingerprint=\"$query_topn\",database=\"$database\", instance_id=\"$instance\",project_id=\"$project\"}"
    }
   ]
  }
 ]
}