{
 "title": "Google Cloud Spanner - Read Insights",
 "description": "Read Insights dashboard",
 "tags": [ "read-insights" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "pds", "label": "Prometheus", "query": "prometheus" },
   { "name": "project", "label": "Project", "query": { "query": "label_values(project_id)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance_id)" } },
   { "name": "database", "label": "Database", "query": { "query": "label_values(database)" } },
   {
    "name": "read_columns_topn",
    "label": "Top 10 Read Columns",
    "query": {
     "query": "query_result(topk(10, avg_over_time(database_spanner_read_stats_top_avg_cpu_seconds[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total (all reads)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "database_spanner_read_stats_total_avg_cpu_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Execution count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "database_spanner_read_stats_total_execution_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Average Rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "database_spanner_read_stats_total_avg_rows{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Average Client Wait Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "database_spanner_read_stats_total_avg_client_wait_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Average Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "database_spanner_read_stats_total_avg_bytes{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Average Leader Refresh Delay Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "database_spanner_read_stats_total_avg_leader_refresh_delay_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Average Locking Delay Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "database_spanner_read_stats_total_avg_locking_delay_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Reads (per read)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (project_id,instance_id,database,read_columns,fingerprint)(database_spanner_read_stats_top_avg_cpu_seconds{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
       "legendFormat": "{{read_columns}}"
      }
     ]
    },
    {
     "title": "Execution count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (project_id,instance_id,database,read_columns,fingerprint)(database_spanner_read_stats_top_execution_count{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
       "legendFormat": "{{read_columns}}"
      }
     ]
    },
    {
     "title": "Average Rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "avg by (project_id,instance_id,database,read_columns,fingerprint)(database_spanner_read_stats_top_avg_rows{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
       "legendFormat": "{{read_columns}}"
      }
     ]
    },
    {
     "title": "Average Client Wait Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (project_id,instance_id,database,read_columns,fingerprint)(database_spanner_read_stats_top_avg_client_wait_seconds{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
       "legendFormat": "{{read_columns}}"
      }
     ]
    },
    {
     "title": "Average Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (project_id,instance_id,database,read_columns,fingerprint)(database_spanner_read_stats_top_avg_bytes{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
       "legendFormat": "{{read_columns}}"
      }
     ]
    },
    {
     "title": "Average Leader Refresh Delay Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (project_id,instance_id,database,read_columns,fingerprint)(database_spanner_read_stats_top_avg_leader_refresh_delay_seconds{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
       "legendFormat": "{{read_columns}}"
      }
     ]
    },
    {
     "title": "Average Locking Delay Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (project_id,instance_id,database,read_columns,fingerprint)(database_spanner_read_stats_top_avg_locking_delay_seconds{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
       "legendFormat": "{{read_columns}}"
      }
     ]
    },
    {
     "title": "Top Reads",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "database_spanner_read_stats_top_avg_cpu_seconds{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"}"
      },
      {
       "expr": "database_spanner_read_stats_top_execution_count{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"}"
      }
     ]
    }
   ]
  }
 ]
}